apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeproject-root
  namespace: argocd
spec:
  project: kubeproject

  source:
    repoURL: https://github.com/lderdzyan/Kubernetes-Style-Project.git
    targetRevision: HEAD
    path: argocd/apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true