apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-dev
  namespace: argocd
spec:
  project: kubeproject

  source:
    repoURL: https://github.com/lderdzyan/Kubernetes-Style-Project.git
    targetRevision: dev
    path: charts/frontend
    helm:
      valueFiles:
        - environments/dev/frontend-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-staging
  namespace: argocd
spec:
  project: kubeproject

  source:
    repoURL: https://github.com/lderdzyan/Kubernetes-Style-Project.git
    targetRevision: staging
    path: charts/frontend
    helm:
      valueFiles:
        - environments/staging/frontend-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
spec:
  project: kubeproject

  source:
    repoURL: https://github.com/lderdzyan/Kubernetes-Style-Project.git
    targetRevision: prod
    path: charts/frontend
    helm:
      valueFiles:
        - environments/prod/frontend-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

syncPolicy:
  syncOptions:
    - CreateNamespace=true